### ISSUE TITLE
problem building hxScout on Mac 64bit

### ISSUE THREAD

**Issue by mpoint4u** [jcward/hxScout#41]
Just tried to build the latest git version of hxScout ... and I quickly learned, that I needed to import the hxtelemetry library (and even symbolic-link the hxtelemetry folder of that library to the lib folder in hxScout) ...then it starts to build right, but then I get errors like these...

// ***************** start copy & paste ********************* //
xcrun --sdk macosx10.9 clang++ -Iobj/darwin64//__pch/haxe -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/lib/haxe/lib/hxcpp/3,1,39/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_STACK_TRACE -DHXCPP_API_LEVEL=311 -x c++ -frtti ./src/hxtelemetry/Timing.cpp -oobj/darwin64/07fdb186_Timing.o
xcrun --sdk macosx10.9 clang++ -Iobj/darwin64//__pch/haxe -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/usr/lib/haxe/lib/hxcpp/3,1,39/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_STACK_TRACE -DHXCPP_API_LEVEL=311 -x c++ -frtti ./src/hxtelemetry/Config.cpp -oobj/darwin64/07fdb186_Config.o
Error: ./src/hxtelemetry/HxTelemetry.cpp:163:5: error: no member named '__hxcpp_hxt_start_telemetry' in the global namespace
                ::__hxcpp_hxt_start_telemetry();
                ~~^
./src/hxtelemetry/HxTelemetry.cpp:167:6: error: no member named '__hxcpp_hxt_ignore_allocs' in the global namespace
                        ::__hxcpp_hxt_ignore_allocs((int)-1);
                        ~~^
./src/hxtelemetry/HxTelemetry.cpp:217:5: error: no member named '__hxcpp_hxt_ignore_allocs' in the global namespace
                ::__hxcpp_hxt_ignore_allocs((int)1);
                ~~^
./src/hxtelemetry/HxTelemetry.cpp:221:6: error: no member named '__hxcpp_hxt_dump_names' in the global namespace
                        ::__hxcpp_hxt_dump_names(this->_method_names);
                        ~~^
./src/hxtelemetry/HxTelemetry.cpp:244:6: error: no member named '__hxcpp_hxt_dump_samples' in the global namespace
                        ::__hxcpp_hxt_dump_samples(this->_samples);
                        ~~^
./src/hxtelemetry/HxTelemetry.cpp:322:7: error: no member named '__hxcpp_hxt_dump_allocations' in the global namespace
                                ::__hxcpp_hxt_dump_allocations(this->_alloc_types,this->_alloc_details,this->_alloc_stackidmap);
                                ~~^
./src/hxtelemetry/HxTelemetry.cpp:395:18: error: no member named '__hxcpp_hxt_dump_gctime' in the global namespace
                int gctime = ::__hxcpp_hxt_dump_gctime();               HX_STACK_VAR(gctime,"gctime");
                             ~~^
./src/hxtelemetry/HxTelemetry.cpp:415:5: error: no member named '__hxcpp_hxt_ignore_allocs' in the global namespace
                ::__hxcpp_hxt_ignore_allocs((int)-1);
                ~~^
./src/hxtelemetry/HxTelemetry.cpp:461:5: error: no member named '__hxcpp_hxt_ignore_allocs' in the global namespace
                ::__hxcpp_hxt_ignore_allocs((int)1);
                ~~^
./src/hxtelemetry/HxTelemetry.cpp:500:5: error: no member named '__hxcpp_hxt_ignore_allocs' in the global namespace
                ::__hxcpp_hxt_ignore_allocs((int)-1);
                ~~^
10 errors generated. 

// ***************** stop copy & paste ********************* //

...could it be, that I have an old version of hxcpp, or OpenFL or so ... ?!?

**Comment by mpoint4u** [comment]
btw, I use 'lime test "project.xml" mac -64'   in the src/client - folder of hxScout to build the client ...

**Comment by jcward** [comment]
Hi Marcus, you can either:

1) Go back to rev 0d9793ddd813, OR
2) comment out the hxtelemetry dependency and codeblocks, OR
3) use my github versions of hxcpp (integration branch) and hxtelemetry (master branch). I'll try to post instructions soon!

Sorry for the breakage!

**Comment by mpoint4u** [comment]
Hi Jeff,
no problem, I see - the whole thing is still in full swing - I mean ... alpha development... 
... Think I will go for option 3) then...

**Comment by mpoint4u** [comment]
... I even recall, that I read somewhere, that you wanted to build hooks for hxtelementry into hxcpp, though... but that was already 2-3 weeks ago, forgot about it afterwards, and now -  BANG...  that's what I missed here... )) 
So, I will use your fork of hxcpp then...

**Comment by jcward** [comment]
Yeah, things are still under heavy development and may break again, which is why I haven't communicated the instructions yet. But if you're alright with the occasional hiccup, I'm happy to hear how it goes for you!

I may need to check in my openfl before that works.  There's a lot to juggle!

**Comment by mpoint4u** [comment]
ok, so I will be your guinea-pig for MacOS X alpha testing then... )))

**Comment by mpoint4u** [comment]
let me know, when you checked in your OpenFL changes, OK? thanks

**Comment by jcward** [comment]
Marcus - I've just pushed up my [openfl `hxt_prototyping` branch](https://github.com/jcward/openfl/tree/hxt_prototyping).

*Disclaimers:* It is not integration-quality, it's just a prototyping playground.  It has a dependency on hxtelemetry (which won't be the case later.) Things will definitely change.

But... it could get you started. The openfl projects you use need to define HXCPP_TELEMETRY. See the [demo project](https://github.com/jcward/hxtelemetry/tree/master/test/DisplayingABitmap) for reference.

If you have hxscout running, then the demo project, you should see it working like this:

![demo_project](https://cloud.githubusercontent.com/assets/2192439/6012780/8abc4aec-ab09-11e4-9a89-c1666e53d039.jpg)

LMK if you run into trouble. I'm currently working on performance and deallocations.

Cheers,
-Jeff

**Comment by jcward** [comment]
Marcus, I've posted some instructions for building here:

https://gist.github.com/jcward/7608910e6f227cd477c5

**Comment by mpoint4u** [comment]
Hello Jeff, thanks for the instructions ... I will give it a try this
evening ... I'll report, how it went, and where eventual hickups have
occurred ... I'll try on Windows first & then have a try on MacOSX and/or
Linux ...

**Comment by mpoint4u** [comment]
Hi Jeff, I had a first try yd evening, I started out to replicate your
parameters in a cleaned up Windows7 - VirtualMachine (on VmwareFusion
6.0.5) ...

First roadblock came quite early, as I have not able to install & setup
OpenFL 2.1.7 on Win7 through 'haxelib install openfl 2.1.7'

I mean, I downloads and copies all the dependencies in place, but when I
try to run 'haxelib run openfl setup' afterwards, it complains about a
missing openfl.exe file in the templates/bin - subfolder ...

... looks like, I have to build openfl.exe for myself ... (?!?)
I asked Joshua on Twitter, where instructions can be found on how to do
that...

(maybe it's healthy anyway, to be forced to do that for yourself one
time...)

however, if you sended me over your openfl.exe (from the templates/bin
folder of your openfl installation,
I will be quicker on the move towards testing & debugging hxScout on cpp
targets, etc ..

So, some trivial problems so far,
hear you as things go further ...

cheers,
Marcus


>

**Comment by jcward** [comment]
Hi Marcus,

Thanks for trying this. Hmm, my `openfl/templates/bin` has an `openfl.bat` but not an `openfl.exe`. But here's a zip file of my Windows 7 openfl 2,1,7 directory: http://onetacoshort.com/temp/openfl_2,1,7.zip

Unzip it in `haxe/lib/openfl`

It also may not absolutely necessary to use 2.1.7, it's just what I was using. The latest version may work fine.

Best,
-Jeff

**Comment by mpoint4u** [comment]
Ok, got you, I'll have a look later this evening...

**Comment by jcward** [comment]
I believe this should be fixed, closing.
