### ISSUE TITLE
Trace rest parameters not working

### ISSUE THREAD

**Issue by loudoweb** [jcward/hxScout#70]
if you have a trace with rest parameters : trace("test","ok") it only shows "test" in the trace.

**Comment by jcward** [comment]
Ah, thanks for the report!

**Comment by jcward** [comment]
Huh, I have no idea why this is the case. I'm overriding `haxe.Log.trace` as specified in the docs / comments:

https://github.com/HaxeFoundation/haxe/blob/development/std/haxe/Log.hx#L36-L45

I'm also not finding any info about "rest parameters" in haxe in general.

**Comment by jcward** [comment]
Nevermind, got it, fixed in hxtelemetry
